SILENCE_PAD = "[SILENCE_PAD]"
UTTERANCE_PAD = "[UTTERANCE_PAD]"
WORD_PAD = "[WORD_PAD]"
EPAD = "[EPAD]"
EOU = "[EOU]"
BC_TOKEN = "[BC]"
INTER_TOKEN = "[INTER]"

TEXT_STREAM_TOKENS = [
    SILENCE_PAD,
    UTTERANCE_PAD,
    WORD_PAD,
    EPAD,
    EOU,
    BC_TOKEN,
    INTER_TOKEN,
]
